  <?php include "header.php" ?>
    <?php include 'home.php' ?>
    <?php include 'about.php' ?>
    <?php include 'work1.php' ?>
    <?php include 'work2.php' ?>
    <?php include 'work3.php' ?>
    <?php include 'work4.php' ?>
    <?php include 'work5.php' ?>
    <?php include 'work6.php' ?>
    <?php include 'contact.php' ?>
  <?php include 'footer.php' ?>
